export type AbilityScores = {
  logic: number;
  expression: number;
  spatialDesign: number;
  interpersonal: number;
};

export type InterestScores = {
  handsOn: number;
  research: number;
  creation: number;
  helping: number;
  leadership: number;
  detail: number;
};

export type AssessmentResponseInput = {
  studentName: string;
  school?: string;
  studentNumber: string;
  contactInfo: string;
  educationStage: string;
  grade: string;
  gender: string;
  collegeMajor: string;
  hometown?: string;
  mastersIntention: string;
  mastersPlan?: string;
  phdIntention: string;
  phdPlan?: string;
  doctoralCareerDirection: string;
  doctoralCareerOther?: string;
  educationPathReasons: string[];
  educationPathReasonOther?: string;
  fiveYearCity: string;
  fiveYearIncome: string;
  fiveYearIndustry: string;
  fiveYearRole: string;
  fiveYearFamilyStatus: string;
  fiveYearHousingPlan: string;
  fiveYearHobbiesSkills: string;
  tenYearCity: string;
  tenYearIncome: string;
  tenYearIndustry: string;
  tenYearRole: string;
  tenYearFamilyStatus: string;
  tenYearHousingPlan: string;
  tenYearHobbiesSkills: string;
  topValuesRanked: string[];
  abilityScores: AbilityScores;
  interestScores: InterestScores;
  currentGpa?: string;
  gpaScale?: string;
  majorRank?: string;
  majorTotal?: string;
  englishCertificates?: string;
  academicExperiences?: string;
  failedCourseStatus: string;
  hasSecondMajor: string;
  secondMajorName?: string;
  secondMajorProgress?: string;
  secondMajorCareerInterest?: string;
  hasTransferredMajor: string;
  originalMajorName?: string;
  transferReason?: string;
  originalMajorRetainedSkills?: string;
  praisedTraits: string[];
  traitEvidence?: string;
  immersiveActivities?: string;
  favoriteKnowledgeAreas?: string;
  selfDrivenActivities?: string;
  preferredWorkStyle: string[];
  currentPreparations: string[];
  currentPreparationOther?: string;
  preparationDetails?: string;
  missingResources: string[];
  majorOutcomeAwareness: string;
  targetJobAwareness: string;
  jobInfoChannels: string[];
  jobInfoChannelOther?: string;
  healthEnergyStatus: string;
  exerciseFrequency?: string;
  longTermPersistence: number;
  executionStyle: string;
  executionCase?: string;
  failureRecoveryTime: string;
  negativeFeedbackReaction?: string;
  selfDoubtFrequency: string;
  problemSolvingStyle: string;
  supportNeed: string;
  highIntensityExperience: string;
  routineWorkTolerance: string;
  careerRiskPreference: string;
  careerConfusions: string[];
  careerConfusionOther?: string;
  mainConfusionText?: string;
};

export type AssessmentResponse = AssessmentResponseInput & {
  id: string;
  userId: string;
  submittedAt: string;
  createdAt: string;
};
